site_name: 3W6 - Programmation Web Transactionnelle
site_author: Thierry Giroux Veilleux
theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
plugins:
  - with-pdf:
      toc_title: sommaire
      copyright: Tous droits réservés
      cover_subtitle: 420-3W6-EM
      output_path: pdf/420-3W6-EM.pdf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes